/**
 * Kawaii Cursors — Main Frontend Script
 * Handles: cursor preview, filter, search, upload, admin panel, theme toggle
 */

'use strict';

// ─── CONFIG ───────────────────────────────────────────────────────────────────
const API_BASE = 'srv-d7qqkp67r5hc738tjk1g';
const ADMIN_PASSWORD = 'kawaii123';

// ─── DEFAULT CURSOR DATA ──────────────────────────────────────────────────────
const DEFAULT_CURSORS = [
  // ANIMATED
  { id: 1, name: 'Sparkle Trail',    cat: 'animated',   emoji: '✨', type: 'builtin' },
  { id: 2, name: 'Rainbow Dash',     cat: 'animated',   emoji: '🌈', type: 'builtin' },
  { id: 3, name: 'Star Burst',       cat: 'animated',   emoji: '⭐', type: 'builtin' },
  // ANIME
  { id: 4, name: 'Sakura Petal',     cat: 'anime',      emoji: '🌸', type: 'builtin' },
  { id: 5, name: 'Chibi Cat',        cat: 'anime',      emoji: '🐱', type: 'builtin' },
  { id: 6, name: 'Sailor Star',      cat: 'anime',      emoji: '⚡', type: 'builtin' },
  // GAMES
  { id: 7, name: 'Pixel Sword',      cat: 'games',      emoji: '⚔️', type: 'builtin' },
  { id: 8, name: 'Power Up',         cat: 'games',      emoji: '🎮', type: 'builtin' },
  { id: 9, name: 'Heart Life',       cat: 'games',      emoji: '❤️', type: 'builtin' },
  // FUNNY
  { id: 10, name: 'LOL Face',        cat: 'funny',      emoji: '😂', type: 'builtin' },
  { id: 11, name: 'Doge Cursor',     cat: 'funny',      emoji: '🐕', type: 'builtin' },
  { id: 12, name: 'Clown Click',     cat: 'funny',      emoji: '🤡', type: 'builtin' },
  // FUTURISTIC
  { id: 13, name: 'Plasma Ring',     cat: 'futuristic', emoji: '💫', type: 'builtin' },
  { id: 14, name: 'Void Pointer',    cat: 'futuristic', emoji: '🔮', type: 'builtin' },
  { id: 15, name: 'Laser Dot',       cat: 'futuristic', emoji: '🎯', type: 'builtin' },
  // AI CURSORS
  { id: 16, name: 'Neon Glow Cursor',cat: 'ai',         emoji: '🌟', type: 'builtin', desc: 'A soft neon glow pulses around every click — generated by AI' },
  { id: 17, name: 'RGB Trail Cursor',cat: 'ai',         emoji: '🌀', type: 'builtin', desc: 'Leaves a full RGB spectrum trail as you move — AI crafted' },
  { id: 18, name: 'Cyber Eye Cursor',cat: 'ai',         emoji: '👁️', type: 'builtin', desc: 'A sleek cyberpunk eye that tracks your every movement' },
];

// ─── STATE ────────────────────────────────────────────────────────────────────
let allCursors = [...DEFAULT_CURSORS];
let activeFilter = 'all';
let searchQuery = '';
let activeCursorUrl = null;
let isAdminLoggedIn = false;
let currentModalCursor = null;
let uploadedCursors = []; // from backend

// ─── DOM REFS ─────────────────────────────────────────────────────────────────
const $ = id => document.getElementById(id);
const $$ = sel => document.querySelectorAll(sel);

// ─── INIT ─────────────────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  initLoader();
  initParticles();
  initHeader();
  initThemeToggle();
  initFilters();
  initSearch();
  initUpload();
  initModal();
  initAdmin();
  initHamburger();
  loadUploadedCursors();
  renderGrid();
  updateStats();
});

// ─── LOADER ───────────────────────────────────────────────────────────────────
function initLoader() {
  const loader = $('loader');
  setTimeout(() => {
    loader.classList.add('hidden');
    document.body.style.overflow = '';
  }, 2000);
  document.body.style.overflow = 'hidden';
}

// ─── PARTICLES ────────────────────────────────────────────────────────────────
function initParticles() {
  const container = $('particles');
  const count = 25;
  const emojis = ['✦', '✧', '★', '♡', '◆'];

  for (let i = 0; i < count; i++) {
    const p = document.createElement('div');
    p.classList.add('particle');
    p.style.setProperty('--dur', `${6 + Math.random() * 10}s`);
    p.style.setProperty('--delay', `${Math.random() * 8}s`);
    p.style.left = `${Math.random() * 100}%`;
    p.style.background = Math.random() > 0.5 ? 'var(--pink)' : 'var(--purple)';
    if (Math.random() > 0.7) {
      p.style.background = 'none';
      p.style.width = 'auto';
      p.style.height = 'auto';
      p.style.fontSize = '0.8rem';
      p.textContent = emojis[Math.floor(Math.random() * emojis.length)];
      p.style.color = Math.random() > 0.5 ? 'var(--pink)' : 'var(--purple)';
    }
    container.appendChild(p);
  }
}

// ─── HEADER SCROLL ────────────────────────────────────────────────────────────
function initHeader() {
  const header = $('header');
  window.addEventListener('scroll', () => {
    header.classList.toggle('scrolled', window.scrollY > 40);
  }, { passive: true });
}

// ─── HAMBURGER ────────────────────────────────────────────────────────────────
function initHamburger() {
  const btn = $('hamburger');
  const menu = $('mobileMenu');
  btn.addEventListener('click', () => {
    btn.classList.toggle('open');
    menu.classList.toggle('open');
  });
  $$('.mobile-link').forEach(link => {
    link.addEventListener('click', () => {
      btn.classList.remove('open');
      menu.classList.remove('open');
    });
  });
}

// ─── THEME TOGGLE ─────────────────────────────────────────────────────────────
function initThemeToggle() {
  const btn = $('themeToggle');
  const icon = btn.querySelector('.theme-icon');
  const saved = localStorage.getItem('kc-theme') || 'dark';
  document.documentElement.setAttribute('data-theme', saved);
  icon.textContent = saved === 'dark' ? '🌙' : '☀️';

  btn.addEventListener('click', () => {
    const current = document.documentElement.getAttribute('data-theme');
    const next = current === 'dark' ? 'light' : 'dark';
    document.documentElement.setAttribute('data-theme', next);
    icon.textContent = next === 'dark' ? '🌙' : '☀️';
    localStorage.setItem('kc-theme', next);
  });
}

// ─── FILTERS ──────────────────────────────────────────────────────────────────
function initFilters() {
  $$('.filter-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      $$('.filter-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      activeFilter = btn.dataset.cat;
      renderGrid();
    });
  });
}

// ─── SEARCH ───────────────────────────────────────────────────────────────────
function initSearch() {
  const input = $('searchInput');
  let debounce;
  input.addEventListener('input', () => {
    clearTimeout(debounce);
    debounce = setTimeout(() => {
      searchQuery = input.value.trim().toLowerCase();
      renderGrid();
    }, 200);
  });
}

// ─── RENDER GRID ──────────────────────────────────────────────────────────────
function renderGrid() {
  const grid = $('cursorGrid');
  const empty = $('emptyState');

  // Merge default + uploaded cursors
  const combined = [...allCursors, ...uploadedCursors];

  const filtered = combined.filter(c => {
    const catMatch = activeFilter === 'all' || c.cat === activeFilter;
    const searchMatch = !searchQuery || c.name.toLowerCase().includes(searchQuery);
    return catMatch && searchMatch;
  });

  if (filtered.length === 0) {
    grid.innerHTML = '';
    empty.hidden = false;
    return;
  }
  empty.hidden = true;
  grid.innerHTML = filtered.map((c, i) => buildCard(c, i)).join('');

  // Attach card events
  grid.querySelectorAll('[data-preview]').forEach(btn => {
    btn.addEventListener('click', () => openModal(parseInt(btn.dataset.preview)));
  });
  grid.querySelectorAll('[data-download]').forEach(btn => {
    btn.addEventListener('click', () => downloadCursor(parseInt(btn.dataset.download)));
  });

  updateStats(combined.length);
}

function buildCard(c, index) {
  const delay = (index % 12) * 50;
  const imageHtml = c.type === 'uploaded'
    ? `<img class="card-image" src="${API_BASE}/uploads/${c.filename}" alt="${c.name}" loading="lazy" />`
    : `<div class="card-emoji">${c.emoji}</div>`;

  const uploadedTag = c.type === 'uploaded' ? `<span class="card-uploaded-tag">USER</span>` : '';

  return `
    <div class="cursor-card" style="animation-delay:${delay}ms">
      ${uploadedTag}
      <div class="card-image-wrap">
        ${imageHtml}
      </div>
      <div class="card-body">
        <h3 class="card-title">${c.name}</h3>
        <div class="card-meta">
          <span class="cat-badge ${c.cat}">${catLabel(c.cat)}</span>
        </div>
        <div class="card-actions">
          <button class="card-btn card-btn-preview" data-preview="${c.id}">👁 Preview</button>
          <button class="card-btn card-btn-download" data-download="${c.id}">⬇ Save</button>
        </div>
      </div>
    </div>`;
}

function catLabel(cat) {
  return {
    animated: '🎬 Animated',
    anime: '🌸 Anime',
    games: '🎮 Games',
    funny: '😂 Funny',
    futuristic: '🚀 Future',
    ai: '🤖 AI'
  }[cat] || cat;
}

// ─── STATS ────────────────────────────────────────────────────────────────────
function updateStats(total) {
  const combined = allCursors.length + uploadedCursors.length;
  const n = total ?? combined;
  const el = $('statTotal');
  if (!el) return;
  // Animate count up
  let current = 0;
  const step = Math.ceil(n / 30);
  const timer = setInterval(() => {
    current = Math.min(current + step, n);
    el.textContent = current;
    if (current >= n) clearInterval(timer);
  }, 30);
}

// ─── MODAL / PREVIEW ──────────────────────────────────────────────────────────
function initModal() {
  $('modalClose').addEventListener('click', closeModal);
  $('previewModal').addEventListener('click', e => {
    if (e.target === $('previewModal')) closeModal();
  });
  $('modalApply').addEventListener('click', applyCursorFromModal);
  $('modalDownload').addEventListener('click', downloadFromModal);
  $('resetBtn').addEventListener('click', resetCursor);
}

function openModal(id) {
  const combined = [...allCursors, ...uploadedCursors];
  const cursor = combined.find(c => c.id === id);
  if (!cursor) return;
  currentModalCursor = cursor;

  $('modalName').textContent = cursor.name;
  $('modalCat').textContent = catLabel(cursor.cat);
  $('modalCat').className = `cat-badge ${cursor.cat}`;

  const img = $('modalCursorImg');
  if (cursor.type === 'uploaded') {
    img.src = `${API_BASE}/uploads/${cursor.filename}`;
    img.style.display = 'block';
  } else {
    img.src = '';
    img.style.display = 'none';
    // Show emoji for builtins
    const area = $('modalPreviewArea');
    const existingEmoji = area.querySelector('.modal-emoji');
    if (existingEmoji) existingEmoji.remove();
    const span = document.createElement('div');
    span.className = 'modal-emoji';
    span.style.cssText = 'font-size:5rem;animation:pulse 2s infinite';
    span.textContent = cursor.emoji;
    area.insertBefore(span, area.firstChild);
  }

  $('previewModal').hidden = false;
  document.body.style.overflow = 'hidden';

  // Apply cursor preview immediately on open
  applyCursorPreview(cursor);
}

function closeModal() {
  $('previewModal').hidden = true;
  document.body.style.overflow = '';
}

function applyCursorPreview(cursor) {
  if (cursor.type === 'uploaded') {
    const url = `${API_BASE}/uploads/${cursor.filename}`;
    document.body.style.cursor = `url('${url}'), auto`;
    activeCursorUrl = url;
    showNotification(`✦ Previewing: ${cursor.name}`, 'success');
  } else {
    // For emoji cursors, create a canvas-based cursor
    applyCursorFromEmoji(cursor.emoji, cursor.name);
  }
}

function applyCursorFromModal() {
  if (!currentModalCursor) return;
  applyCursorPreview(currentModalCursor);
  closeModal();
}

function applyCursorFromEmoji(emoji, name) {
  const canvas = document.createElement('canvas');
  canvas.width = 48; canvas.height = 48;
  const ctx = canvas.getContext('2d');
  ctx.font = '36px serif';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText(emoji, 24, 24);
  const url = canvas.toDataURL();
  document.body.style.cursor = `url('${url}') 16 16, auto`;
  activeCursorUrl = url;
  showNotification(`✦ Cursor applied: ${name}`, 'success');
}

function resetCursor() {
  document.body.style.cursor = 'auto';
  activeCursorUrl = null;
  showNotification('↺ Default cursor restored', 'success');
}

function downloadCursor(id) {
  const combined = [...allCursors, ...uploadedCursors];
  const cursor = combined.find(c => c.id === id);
  if (!cursor) return;

  if (cursor.type === 'uploaded') {
    const a = document.createElement('a');
    a.href = `${API_BASE}/uploads/${cursor.filename}`;
    a.download = cursor.filename;
    a.click();
  } else {
    // Download emoji as PNG via canvas
    const canvas = document.createElement('canvas');
    canvas.width = 64; canvas.height = 64;
    const ctx = canvas.getContext('2d');
    ctx.font = '48px serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(cursor.emoji, 32, 32);
    const a = document.createElement('a');
    a.href = canvas.toDataURL('image/png');
    a.download = `${cursor.name.replace(/\s+/g, '-').toLowerCase()}.png`;
    a.click();
    showNotification(`⬇ Downloaded: ${cursor.name}`, 'success');
  }
}

function downloadFromModal() {
  if (!currentModalCursor) return;
  downloadCursor(currentModalCursor.id);
}

// ─── UPLOAD ───────────────────────────────────────────────────────────────────
function initUpload() {
  const dropZone = $('dropZone');
  const fileInput = $('fileInput');
  const uploadBtn = $('uploadBtn');

  // Drag and Drop
  dropZone.addEventListener('dragover', e => {
    e.preventDefault();
    dropZone.classList.add('dragover');
  });
  dropZone.addEventListener('dragleave', () => dropZone.classList.remove('dragover'));
  dropZone.addEventListener('drop', e => {
    e.preventDefault();
    dropZone.classList.remove('dragover');
    const file = e.dataTransfer.files[0];
    if (file) handleFileSelect(file);
  });
  dropZone.addEventListener('click', () => fileInput.click());

  fileInput.addEventListener('change', () => {
    if (fileInput.files[0]) handleFileSelect(fileInput.files[0]);
  });

  uploadBtn.addEventListener('click', handleUpload);
}

let selectedFile = null;

function handleFileSelect(file) {
  const allowed = ['image/png', 'image/x-win-bitmap', 'application/octet-stream'];
  if (!file.type.startsWith('image/') && !file.name.endsWith('.cur') && !file.name.endsWith('.ani')) {
    showNotification('⚠ Please upload a PNG, CUR, or ANI file', 'error');
    return;
  }
  if (file.size > 2 * 1024 * 1024) {
    showNotification('⚠ File too large — max 2MB', 'error');
    return;
  }
  selectedFile = file;
  const preview = $('filePreview');
  preview.hidden = false;
  preview.textContent = `✓ ${file.name} (${(file.size / 1024).toFixed(1)} KB)`;
}

async function handleUpload() {
  const name = $('cursorName').value.trim();
  const cat = $('cursorCategory').value;

  if (!name) { showNotification('⚠ Please enter a cursor name', 'error'); return; }
  if (!cat) { showNotification('⚠ Please select a category', 'error'); return; }
  if (!selectedFile) { showNotification('⚠ Please select a file', 'error'); return; }

  const uploadBtn = $('uploadBtn');
  uploadBtn.disabled = true;
  uploadBtn.innerHTML = '<span style="display:inline-block;animation:spin 1s linear infinite">↺</span> Uploading...';

  const formData = new FormData();
  formData.append('name', name);
  formData.append('category', cat);
  formData.append('cursor', selectedFile);

  try {
    const res = await fetch(`${API_BASE}/upload`, { method: 'POST', body: formData });
    if (!res.ok) throw new Error('Upload failed');
    const data = await res.json();
    showNotification(`🎉 "${name}" uploaded successfully!`, 'success');
    resetUploadForm();
    await loadUploadedCursors();
    renderGrid();
    document.getElementById('gallery').scrollIntoView({ behavior: 'smooth' });
  } catch (err) {
    // If backend is offline, do a local preview instead
    const localCursor = {
      id: Date.now(),
      name,
      cat,
      type: 'local',
      emoji: '📎',
      localUrl: URL.createObjectURL(selectedFile),
      filename: selectedFile.name
    };
    uploadedCursors.push(localCursor);
    showNotification(`✦ "${name}" added locally (backend offline)`, 'success');
    resetUploadForm();
    renderGrid();
  } finally {
    uploadBtn.disabled = false;
    uploadBtn.innerHTML = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg> Upload Cursor';
  }
}

function resetUploadForm() {
  $('cursorName').value = '';
  $('cursorCategory').value = '';
  $('filePreview').hidden = true;
  $('filePreview').textContent = '';
  $('fileInput').value = '';
  selectedFile = null;
}

// ─── LOAD FROM BACKEND ────────────────────────────────────────────────────────
async function loadUploadedCursors() {
  try {
    const res = await fetch(`${API_BASE}/cursors`);
    if (!res.ok) return;
    const data = await res.json();
    // Assign IDs if missing
    uploadedCursors = data.cursors.map((c, i) => ({
      ...c,
      id: c.id || 1000 + i,
      type: 'uploaded'
    }));
    renderGrid();
    updateAdminStats();
  } catch {
    // Backend offline — silently continue with local state
  }
}

// ─── ADMIN PANEL ──────────────────────────────────────────────────────────────
function initAdmin() {
  $('adminLoginBtn').addEventListener('click', attemptAdminLogin);
  $('adminPassword').addEventListener('keydown', e => {
    if (e.key === 'Enter') attemptAdminLogin();
  });
  $('adminLogout').addEventListener('click', adminLogout);
  $('refreshAdmin').addEventListener('click', () => {
    loadUploadedCursors().then(renderAdminTable);
  });
  $('deleteAllBtn').addEventListener('click', deleteAllUploads);
  $('adminFilter').addEventListener('change', renderAdminTable);
}

function attemptAdminLogin() {
  const pw = $('adminPassword').value;
  if (pw === ADMIN_PASSWORD) {
    isAdminLoggedIn = true;
    $('adminLogin').hidden = true;
    $('adminDashboard').hidden = false;
    renderAdminTable();
    updateAdminStats();
    showNotification('🔓 Admin access granted', 'success');
  } else {
    showNotification('❌ Incorrect password', 'error');
    $('adminPassword').style.borderColor = '#ff5555';
    setTimeout(() => ($('adminPassword').style.borderColor = ''), 1500);
  }
}

function adminLogout() {
  isAdminLoggedIn = false;
  $('adminLogin').hidden = false;
  $('adminDashboard').hidden = true;
  $('adminPassword').value = '';
  showNotification('🔒 Logged out', 'success');
}

function updateAdminStats() {
  const combined = [...allCursors, ...uploadedCursors];
  $('adminTotal').textContent = combined.length;
  $('adminUploads').textContent = uploadedCursors.length;
}

function renderAdminTable() {
  const tbody = $('adminTableBody');
  const filterVal = $('adminFilter').value;
  const combined = [...allCursors, ...uploadedCursors];
  const rows = combined.filter(c => filterVal === 'all' || c.cat === filterVal);

  tbody.innerHTML = rows.map(c => `
    <tr>
      <td>
        ${c.type === 'uploaded'
          ? `<img class="admin-thumb" src="${API_BASE}/uploads/${c.filename}" alt="${c.name}" />`
          : `<span class="admin-thumb-emoji">${c.emoji}</span>`}
      </td>
      <td><strong>${c.name}</strong></td>
      <td><span class="cat-badge ${c.cat}">${catLabel(c.cat)}</span></td>
      <td>${c.type === 'uploaded' ? '📁 Uploaded' : '✦ Built-in'}</td>
      <td>
        ${c.type !== 'builtin'
          ? `<button class="btn-delete-row" onclick="deleteRow(${c.id})">🗑 Delete</button>`
          : `<span style="color:var(--text-dim);font-size:0.8rem">Protected</span>`}
      </td>
    </tr>
  `).join('');

  updateAdminStats();
}

window.deleteRow = function(id) {
  if (!confirm('Delete this cursor?')) return;
  uploadedCursors = uploadedCursors.filter(c => c.id !== id);
  // Try to delete from backend
  fetch(`${API_BASE}/cursors/${id}`, { method: 'DELETE' }).catch(() => {});
  renderGrid();
  renderAdminTable();
  showNotification('🗑 Cursor deleted', 'success');
};

function deleteAllUploads() {
  if (!confirm('Delete ALL user-uploaded cursors? This cannot be undone.')) return;
  uploadedCursors = [];
  fetch(`${API_BASE}/cursors`, { method: 'DELETE' }).catch(() => {});
  renderGrid();
  renderAdminTable();
  showNotification('🗑 All uploads cleared', 'success');
}

// ─── NOTIFICATION ─────────────────────────────────────────────────────────────
let notifTimer;
function showNotification(message, type = 'success') {
  const el = $('notification');
  el.textContent = message;
  el.className = `notification ${type} show`;
  clearTimeout(notifTimer);
  notifTimer = setTimeout(() => {
    el.classList.remove('show');
  }, 3200);
}

// ─── EXTENSION DOWNLOAD ───────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  const extBtn = $('downloadExtension');
  if (extBtn) {
    extBtn.addEventListener('click', e => {
      e.preventDefault();
      showNotification('📦 Extension files are in the /extension folder', 'success');
    });
  }
});
